endOfLine: "lf"
insertFinalNewline: true
tabWidth: 4
trailingComma: "es5"
overrides:
  - files: "*.nf"
    options:
      tabWidth: 4
  - files: "modules/*.nf"
    options:
      tabWidth: 4
  - files: "*.{md,yml,yaml,html,css,scss,js,cff}"
    options:
      tabWidth: 2
