endOfLine: "lf"
insertFinalNewline: true
tabWidth: 4
trailingComma: "es5"
overrides:
  - files: "*.nf"
    options:
      tabWidth: 4
  - files: "modules/*.nf"
    options:
      tabWidth: 4
  - files: "*.md"
    options:
      tabWidth: 2
