name: make pretty
on:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install --no-save prettier
        
      - name: Check and format files
        run: npx prettier --check '**/*.{js,jsx,ts,tsx,css,md,json,yml,yaml,html,scss}' && npx prettier --write '**/*.{js,jsx,ts,tsx,css,md,json,yml,yaml,html,scss}'
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Format code with Prettier"
          git push
