name: make pretty
on:
  push:
    branches:
      - main

jobs:
  reformat_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
      
      - name: Check and reformat files
        run: |
          # Find all files in the repository
          FILES=$(find . -type f)

          # Check formatting for each file
          for file in $FILES
          do
            editorconfig-cli check $file
          done

          # Reformat each file
          for file in $FILES
          do
            editorconfig-cli $file
          done

          # Commit and push changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Reformat files with editorconfig"
          git push
