name: lint code with Prettier
on:
  push:
    branches: [ main ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --no-save prettier

      - name: Reformat with Prettier
        run: npx prettier --check ${GITHUB_WORKSPACE}
