name: make pretty
on:
  push:
    branches: [ main ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --no-save prettier

      - name: Reformat with Prettier
        run: npx prettier --write .

      - name: Authenticate with GitHub
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Stage changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
      
      - name: Commit changes
        if: 'git status --porcelain'
        run: |
          git commit -m "Reformat code with Prettier"
          git push origin ${{ github.head_ref }}
