name: Clone and Replace Repository
on:
  repository_dispatch:
    types:
      - create-template-repo
jobs:
  setup-repo:
    if: ${{ github.repository != 'georgiesamaha/testTemplate' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
      
      - name: Configure Git
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Download Test Repository
        run: |
          curl -L -o testTemplate.tar.gz https://github.com/georgiesamaha/testTemplate/archive/refs/heads/main.tar.gz
          tar -zxvf testTemplate.tar.gz
          rm -f testTemplate.tar.gz
          mv testTemplate-main/* .
          rm -rf testTemplate-main
      
      - name: Force push to main
        run: |
          git add .
          git commit -m "Replace repository contents with test repository"
          git push --force

      - name: Create new TEMPLATE branch
        run: |
          git branch TEMPLATE
          git push origin TEMPLATE --force
