name: Clone Separate Repository

on:
  create:
    - repository

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      
      - name: Clone Separate Repository
        run: |
          git clone https://github.com/georgiesamaha/testTemplate.git
