name: Clone Repository from Template

on:
  repository_dispatch:
    types:
      - template

jobs:
  clone_repository:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Template Repository
        run: |
          git clone https://github.com/georgiesamaha/testTemplate .
          rm -rf .git
          git init
          git add .
          git commit -m "Clone template repository"
          git remote add origin "https://github.com/$GITHUB_REPOSITORY"
          git push -u origin main
